### ISSUE TITLE
Replace moment.js lib

### ISSUE THREAD

**Issue by micalevisk** [yuis-ice/notification-cli#3]
Hi!

What do you think about replacing `moment`? It is a [legacy project](https://momentjs.com/docs/#/-project-status) now :/

You can choose any other of these three alternatives here: https://moiva.io/?npm=date-fns+dayjs+luxon+moment

---

#### occurrences

https://github.com/yuis-ice/notification-cli/blob/f8e86e57305c9054adc2634ca784b9d1361dd351/noc.js#L26
https://github.com/yuis-ice/notification-cli/blob/f8e86e57305c9054adc2634ca784b9d1361dd351/noc.js#L33
https://github.com/yuis-ice/notification-cli/blob/f8e86e57305c9054adc2634ca784b9d1361dd351/noc.js#L36
https://github.com/yuis-ice/notification-cli/blob/f8e86e57305c9054adc2634ca784b9d1361dd351/noc.js#L49-L50

If you choose [dayjs](https://github.com/iamkun/dayjs) this project total size will go from [*473.8 kB*](https://bundlephobia.com/scan-results?packages=commander@6.2.1,moment@2.29.1,node-notifier@9.0.0,node-schedule@2.0.0,sleep@6.3.0) to [*191.7 kB*](https://bundlephobia.com/scan-results?packages=commander@6.2.1,dayjs@1.10.4,node-notifier@9.0.0,node-schedule@2.0.0,sleep@6.3.0) :smile:

**Comment by didvc** [comment]
Hey, thanks for the info! that sounds nice, I'll add it to the todo.

**Comment by micalevisk** [comment]
Besides that, I've notice that you're importing `sleep` but aren't using this anywhere. Are you planning to do something with it?

https://github.com/yuis-ice/notification-cli/blob/f8e86e57305c9054adc2634ca784b9d1361dd351/noc.js#L24

**Comment by didvc** [comment]
I also noticed that, so far `sleep` is not used and not planed to used, so better to be removed from package.json/script.js.
